### ISSUE TITLE
Add Item nuk duhet ti kete te gjitha fushat Mandatory

### ISSUE THREAD

**Issue by kuklei** [Klajd17/invoice_app_frontend#1]
![image](https://github.com/Klajd17/invoice_app_frontend/assets/48261728/8c158991-5582-4252-a3a5-d4d41ff6eab8)

**Comment by Klajd17** [comment]
Pershendetje Kleidi,

Te falenderoj per feedback-un.

1- Discount-in e kisha lene 2% per arsye testimi. Po tani eshte ne rregull,
useri mund te ti bej update direkt,.
2- Add Item eshte ne rregull tani, vetem disa fusha jane required.

Faleminderit

[image: image.png]
[image: image.png]

**Comment by kuklei** [comment]
E ben dot save new item ti? Ose dhe update? Leximi i dokumentacioneve te API eshte i rendesishem. Get dhe Post/Put kane objekte te ndryshme por kjo sa per info. Mos harxho me kohe se task quhet i perfunduar. Do te njoftoj deri ne fund te javes. Dhe tjeter, shiko swagger codegen. Do ta kishte bere punen akoma me te lehte

**Comment by Klajd17** [comment]
Pershendetje Kleidi,

Po mund ta bej edhe create edhe update .
[image: 6b0cfdc7-f1e1-4a81-86c0-b96364572581.png]
[image: image.png]

- Ndoshta ne momentin qe zgjedh Item Type: 0, mendoj qe eshte error ne back
kur i dergon 0 (ItemType is required), ne payload un ja dergoj 0, (me Item
Type: 1 funksionon):

[image: image.png]

- Persa i perket faktit te Get dhe Post/Put, normal qe nuk kam perdor
objekte te njejta, po te shikosh ne inicializimin e form group-it te
seciles prej moduleve
 jane perdor ekzaktesisht objektet qe jane ne swagger si per Get dhe
Post/Put.

Faleminderit
